Add all new issues to the PASS-EF Phase 2 Project
eclipse-pass/main pull request #190
Opened 2022-04-19 03:26 UTC by grant-mcs

2022-04-19 13:12 UTC, bbranan commented
Thanks for looking at this @grant-mcs. Let's wait on merging until after the team call today, as we may start using a different project board (so we'd need to change the project number in this PR). Also, it looks like you committed as grant-cf rather than grant-mcs.

2022-04-20 01:24 UTC, grant-mcs commented
Thank you @bbranan for pointing out the username mix-up. I forgot that I hadn't yet configured this repo. It's now been fixed.

For this change, I looked into the available options for assigning issues to a project and found the same as you. The options were either a GitHub app or a GitHub Actions workflow. I opted for the workflow for a few reasons:

1. The configuration is very flexible. GitHub Actions are an integral part of GitHub and they provide many different ways of detecting events around issues as well as full flexibility in handling them.
2. Simplicity. We're not doing very much with issues right now so the resulting workflow file is very small and easy to  understand.
3. "Obviousness". The GitHub app option hides away the logic in the configuration for the app and it seemed likely to act as more of a black box.

2022-04-20 01:30 UTC, aforward approved these changes

2022-04-20 17:06 UTC, bbranan requested changes
Suggested updates to make use of the new project board I just created: https://github.com/orgs/eclipse-pass/projects/4

2022-04-21 13:28 UTC, merged